hljs.registerLanguage("java",function(a){return{aliases:["jsp"],k:"Pattern Matcher false synchronized int abstract float private char boolean static null if const for true while long strictfp finally protected import native final void enum else break transient catch instanceof byte super volatile case assert short package default double public try this switch continue throws protected public private",i:/<\//,c:[{cN:"javadoc",b:"/\\*\\*",e:"\\*/",r:0,c:[{cN:"javadoctag",b:"(^|\\s)@[A-Za-z]+"}]},a.CLCM,
a.CBCM,a.ASM,a.QSM,{cN:"class",bK:"class interface",e:/[{;=]/,eE:!0,k:"class interface",i:/[:"\[\]]/,c:[{bK:"extends implements"},a.UTM]},{bK:"new throw return",r:0},{cN:"function",b:"("+(a.UIR+"(<"+a.UIR+">)?")+"\\s+)+"+a.UIR+"\\s*\\(",rB:!0,e:/[{;=]/,eE:!0,k:"Pattern Matcher false synchronized int abstract float private char boolean static null if const for true while long strictfp finally protected import native final void enum else break transient catch instanceof byte super volatile case assert short package default double public try this switch continue throws protected public private",
c:[{b:a.UIR+"\\s*\\(",rB:!0,r:0,c:[a.UTM]},{cN:"params",b:/\(/,e:/\)/,k:"Pattern Matcher false synchronized int abstract float private char boolean static null if const for true while long strictfp finally protected import native final void enum else break transient catch instanceof byte super volatile case assert short package default double public try this switch continue throws protected public private",r:0,c:[a.ASM,a.QSM,a.CNM,a.CBCM]},a.CLCM,a.CBCM]},{cN:"number",b:"(\\b(0b[01_]+)|\\b0[xX][a-fA-F0-9_]+|(\\b[\\d_]+(\\.[\\d_]*)?|\\.[\\d_]+)([eE][-+]?\\d+)?)[lLfF]?",
r:0},{cN:"annotation",b:"@[A-Za-z]+"}]}});
hljs.registerLanguage("php",function(a){var b={cN:"variable",b:"\\$+[a-zA-Z_\u007f-\u00c3\u00bf][a-zA-Z0-9_\u007f-\u00c3\u00bf]*"},c={cN:"preprocessor",b:/<\?(php)?|\?>/},d={cN:"string",c:[a.BE,c],v:[{b:'b"',e:'"'},{b:"b'",e:"'"},a.inherit(a.ASM,{i:null}),a.inherit(a.QSM,{i:null})]},f={v:[a.BNM,a.CNM]};return{aliases:["php3","php4","php5","php6"],cI:!0,k:"and include_once list abstract global private echo interface as static endswitch array null if endwhile or const for endforeach self var while isset public protected exit foreach throw elseif include __FILE__ empty require_once do xor return parent clone use __CLASS__ __LINE__ else break print eval new catch __METHOD__ case exception default die require __FUNCTION__ enddeclare final try switch continue endfor endif declare unset true false trait goto instanceof insteadof __DIR__ __NAMESPACE__ yield finally",c:[a.CLCM,
a.HCM,a.C("/\\*","\\*/",{c:[{cN:"phpdoc",b:"\\s@[A-Za-z]+"},c]}),a.C("__halt_compiler.+?;",!1,{eW:!0,k:"__halt_compiler",l:a.UIR}),{cN:"string",b:"<<<['\"]?\\w+['\"]?$",e:"^\\w+;",c:[a.BE]},c,b,{b:/(::|->)+[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*/},{cN:"function",bK:"function count print_r preg_match preg_match_all preg_replace",e:/[;{]/,eE:!0,i:"\\$|\\[|%",c:[a.UTM,{cN:"params",b:"\\(",e:"\\)",c:["self",b,a.CBCM,d,f]}]},{cN:"class",bK:"class interface",e:"{",eE:!0,i:/[:\(\$"]/,c:[{bK:"extends implements"},
a.UTM]},{bK:"namespace",e:";",i:/[\.']/,c:[a.UTM]},{bK:"use",e:";",c:[a.UTM]},{b:"=>"},d,f]}});
hljs.registerLanguage("python",function(a){var b={cN:"prompt",b:/^(>>>|\.\.\.) /},c={cN:"string",c:[a.BE],v:[{b:/(u|b)?r?'''/,e:/'''/,c:[b],r:10},{b:/(u|b)?r?"""/,e:/"""/,c:[b],r:10},{b:/(u|r|ur)'/,e:/'/,r:10},{b:/(u|r|ur)"/,e:/"/,r:10},{b:/(b|br)'/,e:/'/},{b:/(b|br)"/,e:/"/},a.ASM,a.QSM]},d={cN:"number",r:0,v:[{b:a.BNR+"[lLjJ]?"},{b:"\\b(0o[0-7]+)[lLjJ]?"},{b:a.CNR+"[lLjJ]?"}]};return{aliases:["py","gyp"],k:{keyword:"and elif is global as in if from raise for except finally print import pass return exec else break not with class assert yield try while continue del or def lambda nonlocal|10 None True False",
built_in:"Ellipsis NotImplemented"},i:/(<\/|->|\?)/,c:[b,d,c,a.HCM,{v:[{cN:"function",bK:"def",r:10},{cN:"class",bK:"class"}],e:/:/,i:/[${=;\n,]/,c:[a.UTM,{cN:"params",b:/\(/,e:/\)/,c:["self",b,d,c]}]},{cN:"decorator",b:/@/,e:/$/},{b:/\b(print|exec)\(/}]}});
hljs.registerLanguage("cs",function(a){var b=a.IR+"(<"+a.IR+">)?";return{aliases:["csharp"],k:"abstract as base bool break byte case catch char checked const continue decimal dynamic default delegate do double else enum event explicit extern false finally fixed float for foreach goto if implicit in int interface internal is lock long null when object operator out override params private protected public readonly ref sbyte sealed short sizeof stackalloc static string struct switch this true try typeof uint ulong unchecked unsafe ushort using virtual volatile void while async protected public private internal ascending descending from get group into join let orderby partial select set value var where yield",i:/::/,
c:[a.C("///","$",{rB:!0,c:[{cN:"xmlDocTag",v:[{b:"///",r:0},{b:"\x3c!--|--\x3e"},{b:"</?",e:">"}]}]}),a.CLCM,a.CBCM,{cN:"preprocessor",b:"#",e:"$",k:"if else elif endif define undef warning error line region endregion pragma checksum"},{cN:"string",b:'@"',e:'"',c:[{b:'""'}]},a.ASM,a.QSM,a.CNM,{bK:"class namespace interface",e:/[{;=]/,i:/[^\s:]/,c:[a.TM,a.CLCM,a.CBCM]},{bK:"new return throw await",r:0},{cN:"function",b:"("+b+"\\s+)+"+a.IR+"\\s*\\(",rB:!0,e:/[{;=]/,eE:!0,k:"abstract as base bool break byte case catch char checked const continue decimal dynamic default delegate do double else enum event explicit extern false finally fixed float for foreach goto if implicit in int interface internal is lock long null when object operator out override params private protected public readonly ref sbyte sealed short sizeof stackalloc static string struct switch this true try typeof uint ulong unchecked unsafe ushort using virtual volatile void while async protected public private internal ascending descending from get group into join let orderby partial select set value var where yield",
c:[{b:a.IR+"\\s*\\(",rB:!0,c:[a.TM],r:0},{cN:"params",b:/\(/,e:/\)/,k:"abstract as base bool break byte case catch char checked const continue decimal dynamic default delegate do double else enum event explicit extern false finally fixed float for foreach goto if implicit in int interface internal is lock long null when object operator out override params private protected public readonly ref sbyte sealed short sizeof stackalloc static string struct switch this true try typeof uint ulong unchecked unsafe ushort using virtual volatile void while async protected public private internal ascending descending from get group into join let orderby partial select set value var where yield",
r:0,c:[a.ASM,a.QSM,a.CNM,a.CBCM]},a.CLCM,a.CBCM]}]}});Date.now||(Date.prototype.now=function(){return(new Date).getTime()});var GA_PAGE_KEY,FOCUS_CONTINUE_BUTTON_ON_COMPLETE=!1,DEBUG=!1,TYPE_SOLUTION_TEXT=!1,FOCUS_ON_SCROLL=!1;function Exercise(a,b,c){this.data=c;this.problems=[];this.problemJqEls=b;this.exerciseJqEl=a;this.editorJqEl=a.find(".exercise_input_field");this.editorLastInput=this.editorInputTimeoutTimer=null;this.continueJqEl=a.find(".continue");this.solutionJqEl=a.find(".solution")}
Exercise.prototype.proxy=function(a){return $.proxy(a,this)};
Exercise.prototype.initialize=function(){$.each(this.data,this.proxy(function(a,b){this.problems.push(new Problem(this.problemJqEls[a],b.type,b.text,"captureData"in b?b.captureData:null))}));this.editorJqEl.on("keydown keyup",this.proxy(function(a){this.requestUpdateFromInput()}));if(FOCUS_ON_SCROLL&&window.innerHeight){var a=this.editorJqEl.offset().top+this.editorJqEl.outerHeight(),b=!1,c=$(window);c.on("scroll",this.proxy(function(){var d=c.scrollTop();!b&&d<=a&&a<=d+window.innerHeight&&(this.editorJqEl.focus(),
b=!0)}))}this.exerciseJqEl.find(".show_solution_button").on("click",this.proxy(function(a){ga("send","event","solution","click",GA_PAGE_KEY);this.solutionJqEl.css("display","block");this.editorJqEl.focus();a.preventDefault();a.stopPropagation()}));this.solutionJqEl.find(".editor_val").on("click",this.proxy(function(a){var b=$(a.target).text();ga("send","event","solution_editor_val","click/"+b,GA_PAGE_KEY);if(TYPE_SOLUTION_TEXT){var c="",e=this.proxy(function(){c.length<b.length?(c=b.substring(0,c.length+
1),this.editorJqEl.val(c),setTimeout(e,10)):(this.requestUpdateFromInput(),this.editorJqEl.focus())},this);setTimeout(e,10)}else this.editorJqEl.focus(),this.editorJqEl.val(b),this.requestUpdateFromInput();a.preventDefault();a.stopPropagation()}))};
Exercise.prototype.requestUpdateFromInput=function(){null!=this.editorInputTimeoutTimer&&clearTimeout(this.editorInputTimeoutTimer);this.editorInputTimeoutTimer=setTimeout(this.proxy(function(){this.updateFromInput();this.editorInputTimeoutTimer=null}),64)};
Exercise.prototype.updateFromInput=function(){if(DEBUG)var a=Date.now();var b=this.editorJqEl.val();if(b!=this.editorLastInput){b=this.recurseCompletePattern(b,0,b.length,null)[1];DEBUG&&console.log(b);var c=!0;$.each(this.problems,this.proxy(function(a,f){c=f.verifyInput(b)&&c}));c?(ga("send","event","lesson","completed/"+b,GA_PAGE_KEY),this.enableContinueButton()):this.disableContinueButton();this.editorLastInput=b;DEBUG&&console.log("updateFromInput",Date.now()-a)}};
Exercise.prototype.enableContinueButton=function(){this.continueJqEl.removeClass("disabled");this.continueJqEl.removeAttr("disabled");FOCUS_CONTINUE_BUTTON_ON_COMPLETE&&this.continueJqEl.focus()};Exercise.prototype.disableContinueButton=function(){this.continueJqEl.addClass("disabled");this.continueJqEl.attr("disabled","1")};
Exercise.prototype.recurseCompletePattern=function(a,b,c,d){for(var f="",k=c,e=b;e<=c;e++){var g="";0<e&&(g=a.charAt(e-1));var h=a.charAt(e);if(e==c){null!=d&&(f+=d);break}if(")"==d&&"}"==h&&"\\"!=g||")"==d&&"]"==h&&"\\"!=g||"]"==d&&")"==h&&"\\"!=g||"]"==d&&"}"==h&&"\\"!=g||"}"==d&&"]"==h&&"\\"!=g||"}"==d&&")"==h&&"\\"!=g){f+=d;k=e;break}else if(h==d&&e<c){f+=h;k=e+1;break}else if("("==h&&"\\"!=g)g=this.recurseCompletePattern(a,e+1,c,")"),f+=h+g[1],e+=g[0];else if("["==h&&"\\"!=g)g=this.recurseCompletePattern(a,
e+1,c,"]"),f+=h+g[1],e+=g[0];else if("{"==h&&"\\"!=g)g=this.recurseCompletePattern(a,e+1,c,"}"),f+=h+g[1],e+=g[0];else if(e<c)f+=h;else break}return[k-b,f]};function Problem(a,b,c,d){this.problemJqEl=a;this.textJqEl=$(a).find(".text");this.resultJqEl=$(a).find(".result");this.groupJqEls=$(a).find(".groups").find(".group");this.type=b;this.text=c;this.captureData=d}Problem.prototype.proxy=function(a){return $.proxy(a,this)};
Problem.prototype.verifyInput=function(a){try{if(0==a.length)return this.clearResult(),!1;var b=this.text.match(new RegExp(a,""));if("match"==this.type||"capture"==this.type){if(null!=b){var c=this.escapeHtml(this.text.substring(0,b.index))+"<span class='match_succeeded'>"+this.escapeHtml(b[0])+"</span>"+this.escapeHtml(this.text.substring(b.index+b[0].length,this.text.length));this.textJqEl.html(c);if(this.captureData){var d=b.slice(1,b.length),f=_.intersection(d,this.captureData.results),k=_.difference(this.captureData.results,
f);$.each(this.groupJqEls,this.proxy(function(a,b){var c=$(b),d=c.text();-1!=_.indexOf(f,d)?this.markGroupMatched(c):-1!=_.indexOf(k,d)&&this.markGroupMissed(c)}));return 0==k.length?this.markSucceeded():this.markFailed()}return this.markSucceeded()}this.clearResult();return this.markFailed()}if("skip"==this.type){if(null==b)return this.clearResult(),!0;c=this.escapeHtml(this.text.substring(0,b.index))+"<span class='match_failed'>"+this.escapeHtml(b[0])+"</span>"+this.escapeHtml(this.text.substring(b.index+
b[0].length,this.text.length));this.textJqEl.html(c);return this.markFailed()}alert("Invalid type")}catch(e){DEBUG&&console.log(e)}return!1};Problem.prototype.markGroupMatched=function(a){a.addClass("succeeded");return!0};Problem.prototype.markGroupMissed=function(a){a.removeClass("succeeded");return!1};Problem.prototype.markSucceeded=function(){this.resultJqEl.html("<img src='/cs/images/task_complete.png' alt='Success' />");this.resultJqEl.removeClass("succeeded failed").addClass("succeeded");return!0};
Problem.prototype.markFailed=function(){this.resultJqEl.html("<img src='/cs/images/task_incomplete.png' alt='Failed' />");this.resultJqEl.removeClass("succeeded failed").addClass("failed");return!1};Problem.prototype.clearResult=function(){this.textJqEl.text(this.text);this.resultJqEl.html("<img src='/cs/images/task_default.png' alt='To be completed' />");this.resultJqEl.removeClass("succeeded failed");this.captureData&&$.each(this.groupJqEls,this.proxy(function(a,b){this.markGroupMissed($(b))}))};
Problem.prototype.escapeHtml=function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")};
function ButtonHoverHelper(a,b,c,d){this.menuJqEl=b;this.lessonJqEl=c;this.practiceJqEl=d;this.lessonMenuVisible=this.menuContainerVisible=!1;this.leaveTimeoutTimer=null;this.forceOpen=!1;a.on("click",this.proxy(this.onBackgroundClick));c.on("click",this.proxy(this.onClickLesson));c.on("mouseenter",this.proxy(this.onMouseEnterLesson));c.on("mouseleave",this.proxy(this.onMouseLeave));d.on("click",this.proxy(this.onClickPractice));d.on("mouseenter",this.proxy(this.onMouseEnterPractice));d.on("mouseleave",
this.proxy(this.onMouseLeave));b.on("mouseenter",this.proxy(this.onMouseEnterMenu));b.on("mouseleave",this.proxy(this.onMouseLeave))}ButtonHoverHelper.prototype.proxy=function(a){return $.proxy(a,this)};ButtonHoverHelper.prototype.onBackgroundClick=function(){this.menuContainerVisible&&(this.hideMenuContainer(),this.forceOpen=!1)};
ButtonHoverHelper.prototype.onClickLesson=function(a){if(this.forceOpen)if(this.lessonMenuVisible)this.onBackgroundClick();else this.showLessonMenu();else this.showLessonMenu(),this.forceOpen=!0;a.preventDefault();a.stopPropagation()};ButtonHoverHelper.prototype.onClickPractice=function(a){if(this.forceOpen)if(this.lessonMenuVisible)this.showPracticeMenu();else this.onBackgroundClick();else this.showPracticeMenu(),this.forceOpen=!0;a.preventDefault();a.stopPropagation()};
ButtonHoverHelper.prototype.onMouseEnterLesson=function(){this.forceOpen||(null!=this.leaveTimeoutTimer&&clearTimeout(this.leaveTimeoutTimer),this.showLessonMenu())};ButtonHoverHelper.prototype.onMouseEnterPractice=function(){this.forceOpen||(null!=this.leaveTimeoutTimer&&clearTimeout(this.leaveTimeoutTimer),this.showPracticeMenu())};ButtonHoverHelper.prototype.onMouseEnterMenu=function(){null!=this.leaveTimeoutTimer&&clearTimeout(this.leaveTimeoutTimer)};
ButtonHoverHelper.prototype.onMouseLeave=function(){this.forceOpen||(null!=this.leaveTimeoutTimer&&clearTimeout(this.leaveTimeoutTimer),this.leaveTimeoutTimer=setTimeout(this.proxy(this.onLeave),250))};ButtonHoverHelper.prototype.onEnter=function(){this.menuJqEl.fadeIn(125,this.proxy(function(){this.menuContainerVisible=!0}))};ButtonHoverHelper.prototype.onLeave=function(){this.hideMenuContainer()};
ButtonHoverHelper.prototype.hideMenuContainer=function(){this.menuJqEl.fadeOut(125,this.proxy(function(){this.menuJqEl.find(".lesson_menu").hide();this.menuJqEl.find(".practice_menu").hide();this.menuContainerVisible=!1}))};ButtonHoverHelper.prototype.showLessonMenu=function(){this.menuContainerVisible?(this.menuJqEl.find(".practice_menu").hide(),this.menuJqEl.find(".lesson_menu").show()):(this.menuJqEl.find(".lesson_menu").show(),this.onEnter());this.lessonMenuVisible=!0};
ButtonHoverHelper.prototype.showPracticeMenu=function(){this.menuContainerVisible?(this.menuJqEl.find(".lesson_menu").hide(),this.menuJqEl.find(".practice_menu").show()):(this.menuJqEl.find(".practice_menu").show(),this.onEnter());this.lessonMenuVisible=!1};
function initializeDocumentLoad(a,b){GA_PAGE_KEY=b;new ButtonHoverHelper($("body"),$(".menu_container"),$(".lesson_button"),$(".more_button"));$(".paypal_donation_button").bind("click",function(a){ga("send","event","paypal_donation","click",GA_PAGE_KEY);$("#paypal_form").submit();a.preventDefault();a.stopPropagation()});$("code[class=java]").each(function(a,b){hljs.highlightBlock(b)});$("code[class=cs]").each(function(a,b){hljs.highlightBlock(b)});$("code[class=python]").each(function(a,b){hljs.highlightBlock(b)});
$("code[class=php]").each(function(a,b){hljs.highlightBlock(b)});var c=JSON.parse(a);$(".exercise").each(function(a,b){(new Exercise($(b),$(".problem"),c)).initialize()});c=null};
